services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\CmsBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CmsBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CmsBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\CmsBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
  Tourze\CmsBundle\Procedure\:
    resource: '../../Procedure/'
    public: true
  Tourze\CmsBundle\Twig\:
    resource: '../../Twig/'

  # 接口绑定到默认空实现，对应 bundle 安装后会通过装饰覆盖
  Tourze\CmsBundle\Service\LikeServiceInterface:
    alias: Tourze\CmsBundle\Service\NullLikeService
  Tourze\CmsBundle\Service\CollectServiceInterface:
    alias: Tourze\CmsBundle\Service\NullCollectService
